import ctypes


class Eob1TextStruct(ctypes.Structure):
    _fields_ = [
        ('SelectOption', ctypes.c_char * 15),  # b'Select Option:')
        ('RestParty', ctypes.c_char * 11),  # b'Rest Party')
        ('MemorizeSpells', ctypes.c_char * 16),  # b'Memorize Spells')
        ('PrayforSpells', ctypes.c_char * 16),  # b'Pray for Spells')
        ('ScribeScrolls', ctypes.c_char * 15),  # b'Scribe Scrolls')
        ('Preferences', ctypes.c_char * 12),  # b'Preferences')
        ('GameOptions', ctypes.c_char * 13),  # b'Game Options')
        ('Exit', ctypes.c_char * 5),  # b'Exit')
        ('LoadGame', ctypes.c_char * 10),  # b'Load Game')
        ('SaveGame', ctypes.c_char * 10),  # b'Save Game')
        ('DropCharacter', ctypes.c_char * 15),  # b'Drop Character')
        ('QuitGame', ctypes.c_char * 10),  # b'Quit Game')
        ('GameOptionsTwo', ctypes.c_char * 14),  # b'Game Options:')
        ('Gamesaved', ctypes.c_char * 16),  # b'\r   Game saved.')
        ('Savegamefailure', ctypes.c_char * 22),  # b'\r Save game\r failure!')
        ('Loadgamefailure', ctypes.c_char * 22),  # b'\r Load game\r failure!')
        ('TunesareON', ctypes.c_char * 14),  # b'Tunes are ON ')
        ('SoundsareON', ctypes.c_char * 15),  # b'Sounds are ON ')
        ('BarGraphsareON', ctypes.c_char * 19),  # b'Bar Graphs are ON ')
        ('MouseisON', ctypes.c_char * 13),  # b'Mouse is ON ')
        ('ON', ctypes.c_char * 3),  # b'ON')
        ('OFF', ctypes.c_char * 4),  # b'OFF')
        ('SelectacharacteLearn', ctypes.c_char * 73),
        # b'\r\r Select a character\r from your party who\r would like to learn\r spells.')
        ('YourPaladinisto', ctypes.c_char * 49),  # b'\r Your Paladin is \r too low a level\r for spells.')
        ('TheMagehasnoSpe', ctypes.c_char * 32),  # b'\r\r The Mage has no\r Spell Book!')
        ('SelectacharactePray', ctypes.c_char * 77),
        # b'\r\r\r Select a character\r from your party\r who would like to\r pray for spells.')
        ('YoudonthaveanyCleric', ctypes.c_char * 59),  # b"\r You don't have\r any Cleric able\r to pray in your\r party.")
        ('YoudonthaveanyMage', ctypes.c_char * 50),  # b"\r You don't have\r any Mage able to\r learn spells.")
        ('AnunconsciousorMage', ctypes.c_char * 56),  # b' An unconscious\r or dead Mage\r cannot memorize\r spells.')
        ('AnunconsciousorCleric', ctypes.c_char * 58),  # b' An unconscious\r or dead Cleric\r cannot pray for\r spells.')
        ('1', ctypes.c_char * 2),  # b'1')
        ('2', ctypes.c_char * 2),  # b'2')
        ('3', ctypes.c_char * 2),  # b'3')
        ('4', ctypes.c_char * 2),  # b'4')
        ('5', ctypes.c_char * 2),  # b'5')
        ('Clear', ctypes.c_char * 6),  # b'Clear')
        ('SpellsAvailable', ctypes.c_char * 18),  # b'Spells Available:')
        ('Yes', ctypes.c_char * 4),  # b'Yes')
        ('No', ctypes.c_char * 3),  # b'No')
        ('Willyourhealers', ctypes.c_char * 35),  # b'\rWill your healers\rheal the party?')
        ('Someoneisstilli', ctypes.c_char * 48),  # b' Someone is still\r injured. Rest\r until healed?')
        ('Restingparty', ctypes.c_char * 15),  # b'Resting party.')
        ('Allcharactersar', ctypes.c_char * 37),  # b'\r All characters\r are fully\r rested.')
        ('Yourpartyneedst', ctypes.c_char * 44),  # b' Your party needs\r to rest to gain\r spells.')
        ('Youcannothavele', ctypes.c_char * 46),  # b' You cannot have\r less than four\r characters.')
        ('AreyousureyouwiExit', ctypes.c_char * 43),  # b' Are you sure you\r wish to exit the\r game?')
        ('Yourpartyisstar', ctypes.c_char * 61),  # b' Your party is\r starving. Do you\r wish to continue\r resting?')
        ('Selectthescroll', ctypes.c_char * 41),  # b'Select the scroll(s)\ryou wish to scribe.')
        ('SelectaMagefrom', ctypes.c_char * 70),
        # b'\r\r\r Select a Mage\r from your party\r who would like to\r scribe spells.')
        ('YoudonthaveanyNoScroll', ctypes.c_char * 44),  # b" You don't have\r any scolls to be\r scribed.")
        ('YoudonthaveanyMage', ctypes.c_char * 52),  # b" You don't have\r any scrolls that\r this Mage needs.")
        ('YoudonthaveanyNoMage', ctypes.c_char * 52),  # b"\r You don't have\r any Mage able to\r scribe scrolls.")
        ('Selectthecharac', ctypes.c_char * 42),  # b' Select the\r character you\r wish to drop.')
        ('AreyousureyouwiSave', ctypes.c_char * 43),  # b' Are you sure you\r wish to SAVE the\r game?')
        ('AreyousureyouwiLoad', ctypes.c_char * 47),  # b' Are you sure you\r wish to LOAD a\r saved game?')
        ('Camp', ctypes.c_char * 6),  # b'Camp:')
        ('PreferencesTwo', ctypes.c_char * 13),  # b'Preferences:')
        ('GameOptions', ctypes.c_char * 14),  # b'Game Options:')
        ('Poisonedpartyme', ctypes.c_char * 46)  # b'Poisoned party\rmembers will die!\rRest anyway?')
    ]
